name: "Setup Docker Registries"
description: "Setup Docker Registries"
inputs:
  dockerhub_user:
    description: "DockerHub User"
    required: true
  dockerhub_token:
    description: "DockerHub Token"
    required: true
  ecr_role_arn:
    description: "ECR Role ARN"
    required: false
  repo:
    description: "Docker Repo to push"
    required: true
outputs:
  dockerhub_repo:
    description: "DockerHub Repository"
    value: washanhanzi/databend-build-tools
  ecr_repo:
    description: "AWS public ECR Repository"
    value: hello-world

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      if: inputs.dockerhub_token
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_user }}
        password: ${{ inputs.dockerhub_token }}
