name: Build Tool

on:
  push:
    branches:
      - build

permissions:
  id-token: write
  contents: read

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup_docker
        id: login
        with:
          repo: build-tool
          ecr_role_arn: ${{ secrets.ECR_ROLE_ARN }}
          dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get rust toolchain version
        id: toolchain
        run: |
          version=$(awk -F'[ ="]+' '$1 == "channel" { print $2 }' scripts/setup/rust-toolchain.toml)
          echo "TOOLCHAIN=${version}" >> $GITHUB_OUTPUT

      - name: Build and publish databend build base image
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: |
            ${{ steps.login.outputs.dockerhub_repo }}:base
            ${{ steps.login.outputs.dockerhub_repo }}:base-${{ steps.toolchain.outputs.TOOLCHAIN }}
          context: ./scripts/setup
          file: ./docker/build-tool/base/Dockerfile
          platforms: linux/amd64, linux/arm64


  dev:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      matrix:
        arch:
          # - x86_64
          - aarch64
        include:
          - arch: aarch64
            platform: linux/arm64
          - arch: x86_64
            platform: linux/amd64
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup_docker
        id: login
        with:
          repo: build-tool
          ecr_role_arn: ${{ secrets.ECR_ROLE_ARN }}
          dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get rust toolchain version
        id: toolchain
        run: |
          version=$(awk -F'[ ="]+' '$1 == "channel" { print $2 }' scripts/setup/rust-toolchain.toml)
          echo "TOOLCHAIN=${version}" >> $GITHUB_OUTPUT

      - name: Build and publish databend build base image
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: |
            ${{ steps.login.outputs.dockerhub_repo }}:dev
            ${{ steps.login.outputs.dockerhub_repo }}:dev-${{ steps.toolchain.outputs.TOOLCHAIN }}
          context: ./scripts/setup
          file: ./docker/build-tool/dev/Dockerfile
          build-args: |
            RUST_TOOLCHAIN=${{ steps.toolchain.outputs.TOOLCHAIN }}
            ARCH=${{matrix.arch}}
          platforms: ${{matrix.platform}}
